### ISSUE TITLE
Create DfE functions

### ISSUE THREAD

**Issue by mdsteiner** [ndphillips/ShinyPsych#10]
Functions for a decisions from experience paradigm. I will change the bandit code a bit and add an option such that one can add gambles from a txt file and not only use random draws from distributions.

**Comment by mdsteiner** [comment]
ok first versions of dfe functions are ready. It's possible to have up to 6 different gambles per trial with unlimited number of outcomes per gamble. Default gambles (the different lists from the papers mentioned in another issue) can be accessed by simply giving the author names as an argument to a function...

**Comment by ndphillips** [comment]
Sweet! Can you do a pull request and include some examples so I can see it in action?

**Comment by mdsteiner** [comment]
Sure I'll do it right away. It's still not optimaly organized because of the paths so all the files used in an app (and some more) are in the app folder as well as in the R folder. To run different number of options (all gamble lists from publications we included use 2 options) you just need to change nOpts at line 56 of DfE_app to the number of options and then on line 85 the fileName argument to one of these:
      `default.list.names <- c("HertwigBarronWeberErev", "Birnbaum",
                              "GloecknerPachur", "BrooksPetersZank", "Rieskamp",
                              "LoomesMoffattSugden", "TwoOptExample",
                              "ThreeOptExample", "FourOptExample",
                              "FiveOptExample", "SixOptExample")`
then it should work...

**Comment by mdsteiner** [comment]
What I forgot to mention is that in all the examples the text with the instructions and all doesn't make any sense since I just added some text to have something in there but I only have the tasks themselves ready and not the apps as a whole (which won't be a big thing to do)...
