### ISSUE TITLE
Add different gamble lists to have some defaults

### ISSUE THREAD

**Issue by mdsteiner** [ndphillips/ShinyPsych#16]
I thought about gambles from

- Hertwig et al. (2004)
- Birnbaum (several publications)
- Brooks, Peters and Zank (2014)
- Glöckner and Pachur (2012)

these are all gambles with no more than two options to choose from but maybe we want to make it possible to have more than two outcome gambles (e.g. six as in the bandit game)...

Any other lists of gambles to include?

**Comment by ndphillips** [comment]
I'd also add Rieskamp (2008). I'll attach them here
[rieskamp2008gambles.txt](https://github.com/ndphillips/ShinyPsych/files/1207981/rieskamp2008gambles.txt)

**Comment by mdsteiner** [comment]
ah yes, I'll add them

**Comment by mdsteiner** [comment]
ok gamble lists are added. I also added the gambles from Loomes, Moffatt and Sugden (2002) just because I had them...
