### ISSUE TITLE
Create a ShinyPsych user guide in markdown

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/ShinyPsych#18]
Write a user guide for using ShinyPsych in markdown.

**Comment by mdsteiner** [comment]
I will first try to set things up as a package because I think it makes sense to use the functions from a package in the guides. What do you think?

**Comment by ndphillips** [comment]
sure!

**Comment by mdsteiner** [comment]
Almost done. Only one tutorial for the check id app left. Then we have tutorials for all the tasks, the survey (each with an example app) and how to create the txt files to create the pages and tasks.
