### ISSUE TITLE
Research reconnecting to apps

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/ShinyPsych#2]
- How can one reconnect to a crashed shiny app? What solutions have people come up with?

**Comment by mdsteiner** [comment]
Unfortunately this won't work for us. It's no possible to use if one needs to sequentially enter stuff to determine where the connection was lost. Also the data that was gathered before the disconnection is nowhere saved temporarily so even if the position could be reconstructed, the data up to that point could not...

**Comment by ndphillips** [comment]
Got it.
