### ISSUE TITLE
in createBanditList function, create possibility to input fixed pop values

### ISSUE THREAD

**Issue by mdsteiner** [ndphillips/ShinyPsych#22]
Additionally to the sampling function give users the possibility to have a fixed set of sequences from which the function selects a specified number, with or without replacement.

**Comment by mdsteiner** [comment]
Now that I've checked the function again, I've seen, that it is already possible to load in a file that contains the pop values and everything, so that every participant could have the same. I think it is easier to stay with this possibility and if someone wants to have a set of fixed distributions to sample from, he could just have a file for each possibility and then sample one of the file names. I think that's easier than letting them specify a list of matrices they'd first have to create. What do you think?

Also there is already the possibility to include a maximum pop value and every value drawn from a sampling distribution higher that this maximum will be set to the maximum value. I will extend this and also include a minimum value, so that one can specify that, e.g., a balloon cannot pop at fewer than 3 pumps.

I will also write a tutorial on how to create such a file.

**Comment by ndphillips** [comment]
Sure that sounds good (a different file for each distribution).

**Comment by mdsteiner** [comment]
I included both possibilities, one can read in only one file, possibly containing several distributions, or several files that are then merged. I'll write and upload a tutorial.
