### ISSUE TITLE
Allow data emailing option

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/ShinyPsych#28]
A while ago I tried to include an option for data to be emailed at the conclusion of the experiment. I was never quite able to make it work, but there must be a way!

I think this would be a good default data saving option for ShinyPsych as it doesn't require users to link a dropbox account, or to save data locally to a folder (which might take them some time to find). Plus, it works whether the app is being run online or offline.

@mdsteiner  Have you looked into the data emailing option? If not, I think it's worth spending a few hours on

**Comment by mdsteiner** [comment]
I have started to look into it some time ago and a potential problem was that mail platform as gmail may block the access if many mails are sent with it. But I will spend some more time to try to figure out if and if yes how it is possible to include this.

**Comment by mdsteiner** [comment]
should work. If so (and  if I haven't misspelled your mail) you should have received an email to your gmail address. sending mails to the unibas adresses doesn't seem to work. but gmail and bluewin (another mail server) worked for me...
