### ISSUE TITLE
Create Questionnaire module

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/ShinyPsych#5]
A shiny module that creates questionnaires

Input can be a text file indicating questions, and possible tags indicating paragraph breaks and page breaks. This is read into the module and ultimately converted to Shiny code.

Example
```
question text \t page \t type \t n.responses \t labels
```

e.g.

```
How much do you like programming? \t 1 \t likert \ 5 \t Not at all, , , , Very much
Did you have fun? \t 1 \t likert \ 2 \t No, Yes
```

- Module may need two inputs: one for instructions, one for actual questions.
    - To keep it simple, can assume that instructions are on one page.

**Comment by mdsteiner** [comment]
Questionnaire module is pretty much ready... I tried to handle as much as possible with functions and now we have enough functions to create and run the app for a questionnaire - I also included some kind of randomization. I'll push things tomorrow so you don't have to merge new commits all the time.

**Comment by ndphillips** [comment]
great!
