### ISSUE TITLE
Update rdrop2!!!!

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/ShinyPsych#52]
@ktrutmann and @mdsteiner , Janine (PhD student in our group who is also using Shiny), just told me that she had a bit of a scare last week. All of us a sudden her data was not being uploaded to dropbox, even though she received messages in Rstudio saying they had been 'successfully uploaded'. Apparently the problem was that Dropbox just had a huge update, which is incompatible with the previous version of rdrop2.

If you install the latest version of rdrop2, it should work fine. So let's all do this, and tell the user to do this in any relevant documentation!

**Comment by mdsteiner** [comment]
I think there's a way of specifying a minimum version of the packages in the dependencies. So I think doing this should fix it. This way users wouldn't need to look through the guides to find this critical information

**Comment by ktrutmann** [comment]
rdrop2 0.8.1 (the latest version) is now a requirement for the ShinyPsych package.
