### ISSUE TITLE
Create Bandit Module

### ISSUE THREAD

**Issue by mdsteiner** [ndphillips/ShinyPsych#6]
Create a Bandit module that takes a txt file or arguments ot specify distributions.

**Comment by mdsteiner** [comment]
One question: what should be the maximum number of options in the bandit task? For now I'm thinking of creating separate functions for every number of arms of bandits because I'm afraid that if I try to make this dynamic it may mess up the layout... So the plan I have now is to create several bandit functions and then create another function that calls them based on user input... But I'm not sure how flexible I can make this stuff because it also has the javascript functions it's working with

**Comment by ndphillips** [comment]
Hmmm, how about up to 6 options in a row? would that work?

**Comment by mdsteiner** [comment]
Yes, 6 should work...

**Comment by mdsteiner** [comment]
One more question:

I'm currently programming a function that creates the outcomes to use in the bandit function. I'm not sure how general I should make it: I could generalize it so much as that people can for each game for each option choose the kind of distribution to choose from or I could fix it, that each game needs to have the same distribution or as third option that only one distribution can be specified for the whole task (i.e. all games come from the same distripution **type**; of course you can still specify the parameters). The more generalizable the "deeper" I need to implement the distribution check which will in the most extreme case be executed for each option of each game and in the least genaral case only once.

I'm just asking because from the programming side we should only have as few checks as possible but as many as necessary... I'm not sure how common it is that you want to compare e.g. an option from a normal to an opiton from a uniform distribution, but if that's commonly done then I should go for the way with the most checks...

**Comment by ndphillips** [comment]
Let's do this: if you want the function to generate outcomes, then all options must have the same distribution. If the user wants different values, they need to specify them as a list of outcome vectors which are passed as an optional argument to the function.

what do you think>

**Comment by mdsteiner** [comment]
sure let's do that, so I'll create a default function with a check at the beginning and another one that's called optionally that will do the checks at the last possible stage.

**Comment by mdsteiner** [comment]
I suggest that for now we go for a maximum of 4 options as 5 and 6 is not very clear (see screenshot with 6 arms)...

**Six armed bandit**
![grafik](https://user-images.githubusercontent.com/26483702/28934719-3e86965c-7882-11e7-9356-c2002acebae3.png)

**Four armed bandit**
![grafik](https://user-images.githubusercontent.com/26483702/28934890-e1dff028-7882-11e7-9e7a-66b9866cec9a.png)

**Comment by ndphillips** [comment]
hmmm, I don't understand why it's not easy to create 6 separate, non-overlapping options. Of course in R it would be really easy. Shouldn't a little CSS do the trick?

But I don't think this is a critical issue as we can of course update this later....right?

**Comment by mdsteiner** [comment]
yes sure I think I can do it by changing some functions, and yes we can change it later also. But the boxes will get quite small... I will do this once I'm through with the rest...

**Comment by mdsteiner** [comment]
Ah I thought I'd anyways do it to have it working the way we planned. The boxes are rather small but we now have bandits from 2 to 6 arms...

![grafik](https://user-images.githubusercontent.com/26483702/28955088-ea99e46a-78e3-11e7-8d41-636cb25f98cc.png)

**Comment by ndphillips** [comment]
looks great!
