### ISSUE TITLE
Create a DevGuide

### ISSUE THREAD

**Issue by ktrutmann** [ndphillips/ShinyPsych#64]
Write up a little markdown file where we can look up what we agreed to regarding future development.

**Comment by ktrutmann** [comment]
- I'll have to figure out what my issue was which the "survey pages" names and write up a solution for it (if it is still a problem.
- Futher we might want to adhere our code as best as possible to some styleguide so that the code looks and reads the same, no matter who wrote it. One possible candidate would be the [Google R Styleguide](https://google.github.io/styleguide/Rguide.xml).

**Comment by mdsteiner** [comment]
I agree with using a styleguide. One not so great thing is that I've named all the functions in the following way: functionName(), which is wrong according to google styleguide which suggests FunctionName() and hadley wickham who suggests function_name(). maybe we can change that later on... But yes, let's use the google styleguide... We anyways will have to go through all the code in the end and streamline/ improve things

**Edit**
We could use this http://adv-r.had.co.nz/Style.html

**Comment by ktrutmann** [comment]
@mdsteiner maybe make sure you agree with everything I've written so far and if so, close this issue. If something new comes up, we should make sure that we agree and then either of us can add it to the document.
