### ISSUE TITLE
Adding a new survey in my local copy of ShinyPsych

### ISSUE THREAD

**Issue by pbrews7933** [ndphillips/ShinyPsych#72]
I'm using the "ShinyPsych" package and want to add my own surveys.  How do I do it?  Do I have to rebuild the ShinyPsych package in my local environment with the added apps? If so is there a .Rproj file to guide me.  Or is their an easier way?
Thanks in advance for your reply.

**Comment by mdsteiner** [comment]
You should be able to create a normal shiny app in a folder and add the file in which you created the survey to that folder (or a subfolder) and then call `createPageList()` with `defaulttxt = FALSE` and the name of your file in the `fileName` argument (if you put your survey file in a subfolder you'll have to specify the path to the file relative to the app.R file)

**Comment by pbrews7933** [comment]
Thanks so much … so `defaulttxt = false` is the magic.
