### ISSUE TITLE
How do I increase the number of questions on a page?

### ISSUE THREAD

**Issue by pbrews7933** [ndphillips/ShinyPsych#73]
It seems to be limited to seven.  I'd like to go higher up to 17 to map to a print version of the survey. Is there a parameter?

**Comment by mdsteiner** [comment]
I couldn't replicate this. Are the page numbers (in the "page" column of your survey.txt file) set to the same page? If I do this, I can add 17 questions on a single page.

**Comment by pbrews7933** [comment]
I have redone this several times but cant get beyond 7.  Do you see anything I'm doing to cause this in the query definitions file?  I don't see anything obvious in the code.
[QLI_III.txt](https://github.com/mdsteiner/ShinyPsych/files/2880812/QLI_III.txt)

**Comment by pbrews7933** [comment]
I've think found the problem.  It appears to be a question text that contains an apostrophe as in "Your family's health?".  It seems to cause a failure in the read routine for the question definitions.  I have simply reworded as "Your family health?"  
Thanks

**Comment by mdsteiner** [comment]
Ah yes. But you actually don't have to rephrase it, I briefly checked and if you put the whole question (e.g., `8. Your family's health?`) into double quotation marks (i.e. `"8. Your family's health?"`), it will also work

**Comment by pbrews7933** [comment]
Thanks for all your help.
