### ISSUE TITLE
Vignettes fail to build on a case-sensitive disk

### ISSUE THREAD

**Issue by DanielEWeeks** [ndphillips/ShinyPsych#74]
When trying to build the vignette on a system with a case-sensitive disk, it fails to build because the picture file is named 'screenshot_bandit.PNG' but the vignette is looking for 'screenshot_bandit.png':

```
* preparing ‘ShinyPsych’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
pandoc: Could not fetch ../inst/pictures/screenshot_bandit.png
../inst/pictures/screenshot_bandit.png: openBinaryFile: does not exist (No such file or directory)
Error: processing vignette 'ShinyPsych_Bandit.Rmd' failed with diagnostics:
pandoc document conversion failed with error 67
Execution halted
```

**Comment by mdsteiner** [comment]
I realised that the file extensions were .PNG. I now changed that to be .png, so it might work now. I can, however, not test it on my system as it worked for me before. Please check now it works and let me know whether that did the trick.
