### ISSUE TITLE
Installing ShinyPsych both in R or Rstudio

### ISSUE THREAD

**Issue by acaciomattos** [ndphillips/ShinyPsych#75]
Hello everyone, i'm having problems installinh ShinyPsych in my computer. I already try a lot of different ways to install, had updated all my packages and still i'm getting an error.
I have all necessary packages installed (at least the log tell nothing about it).

My sessionInfo is:
![image](https://user-images.githubusercontent.com/46786431/58290113-790b2380-7db0-11e9-8e9c-33e43f76102b.png)

The code i used to install is:

![image](https://user-images.githubusercontent.com/46786431/58290166-a35ce100-7db0-11e9-8b3a-b5c0272b7fdf.png)

And the error i'm receiving is:

![image](https://user-images.githubusercontent.com/46786431/58290254-05b5e180-7db1-11e9-9f3a-6548a7066327.png)
![image](https://user-images.githubusercontent.com/46786431/58290271-16665780-7db1-11e9-88b0-ba62774f9969.png)
![image](https://user-images.githubusercontent.com/46786431/58290287-241bdd00-7db1-11e9-90f9-4ec1836ddb2d.png)

The strange thing is that i have already installed the package in another machine. 

Any suggestions? Thanks.

**Comment by mdsteiner** [comment]
I updated the VignetteIndexEntry lines in the vignettes. Please try installing it again and let me know whether now it worked.

**Comment by acaciomattos** [comment]
Im at work right now, but i will check it soon as get home. Thanks in advance!

**Comment by acaciomattos** [comment]
> I updated the VignetteIndexEntry lines in the vignettes. Please try installing it again and let me know whether now it worked.

Almost there! The vignettes seems to be well created, but now the error concerns the DESCRIPTION file i think, or in building 'ShinyPsych_0.2.3.tar.gz' file Here is the error:

![image](https://user-images.githubusercontent.com/46786431/58357348-53465300-7e72-11e9-8266-c286e2779b7b.png)

**Comment by acaciomattos** [comment]
Done! I change the library and it works!
