### ISSUE TITLE
Conditional Questions

### ISSUE THREAD

**Issue by d-bohn** [ndphillips/ShinyPsych#76]
Hello,

Firstly, thank you for proving this package! It has been very useful, particularly for teaching Shiny to students in an easy and digestible way.

I wanted to check on the state of issue #55 (conditional questions feature). I noticed that there is a branch of the repo dedicated to this feature, but it appears not to be working when I cloned that branch. Is that correct? Any timeline for releasing this feature?

Again, thank you!

**Comment by mdsteiner** [comment]
Hi,

thanks for your feedback!

Yes you're correct, it's not yet working. I'm afraid that currently I don't have the time to develop it further next to doing my PhD. Sorry for that... I will let you know once I find time to implement it, but I don't expect it to be within the next couple of months...

**Comment by d-bohn** [comment]
Thanks for the update, and good luck with your PhD!
