### ISSUE TITLE
Add a shiny app in a package

### ISSUE THREAD

**Issue by mdsteiner** [ndphillips/ShinyPsych#8]
I just found a blog post on how to incorporate a shiny app in a package. I'm posting this so we can use it later

https://www.r-bloggers.com/supplementing-your-r-package-with-a-shiny-app-2/

**Comment by ndphillips** [comment]
great!

**Comment by mdsteiner** [comment]
Apps are added in the package and you can now call them with a function named callApp(). Running the apps with this works fine (I just need to change the apps so they don't depend on dropbox and we're not giving the access tokens to everyone).  However showing the code, at least on windows, only works in basic R, not in RStudio (there appears to be some bug with the file.edit function for RStudio).

**Comment by ndphillips** [comment]
Got it.
